services:
  - type: web
    name: sentiment-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: NLTK_DATA
        value: nltk_data
